RevolutionUC/revolutionuc-frontend

- _scss/components/_hero.scss
- _scss/components/_main.scss
Fixes the issues seen in the screenshot in #5. Seems to happen on larger screens or weird window sizes.
> Changed one small boi to fix video sizing on larger screens

- _scss/components/_main.scss
- _scss/components/_section.scss
- _scss/layout/_container.scss
- _scss/pages/_sponsors.scss
- sponsors.html
Sponsor images now lay out two to a row
Move down to one per row on small widths
Background color of sponsor page is white
> Sponsor layout and BG updates

- email-verified.html
> Email verified

- check-email.html
> Check email

- _includes/header.html
- _layouts/homepage.html
- _scss/components/_registration.scss
- _scss/main.scss
- check-email.html
- js/register.js
- register.html
Would like some feedback on this, but tbh I don't wanna change too much as I want to get this up tonight.
Only thing left to do is have some organizers test this (ideally we'd push this up to test.revolutionuc.com for only us cool organizers to use, but tbh I'm not really sure how to do that) and use the live database (which we'd clear before actually releasing), and then push live very soon.
----
Closes #28
> Registration

- _data/schedule.yml
- _includes/header.html
- _scss/components/_schedule.scss
- _scss/main.scss
- schedule.html
Basic template for the schedule
Copied schedule data into .yml file
Added styling to the schedule rows
May need a new image
> Basic schedule, easily editable

- _scss/components/_registration.scss
https://i.imgur.com/PTHsDkp.png
> Updated label locations to top left

- register.html
Stacking the shirt sizes matches the way we handle the dietary restrictions. If we wanted to reject this PR, and keep them side-by-side we'd also have to do some more responsive work, which I'm not necessarily opposed to, just don't know if I have the time to put in.
> Stack shirt sizes

- _scss/components/_registration.scss
- js/register.js
- register.html
We've had a number of messages that their school is not listed on the MLH list.
Note: this is to merge into the snyderks-typeahead branch.
Should close #45
> Add support for 'other' option in selecting school

- _data/faq.yml
I added a travel reimbursement policy. We need to agree that his is acceptable, and that we like my wording.
> Add travel reimbursement policy

- _scss/_variables.scss
- _scss/components/_registration.scss
Will resolve #51.
Added an extra-light version of the purple
Changed mouseover color on typeahead dropdown
Changed highlight color on typeahead searches
> Changed typeahead colors

- _includes/header.html
- _layouts/homepage.html
- index.html
- register.html
Also added a message at the bottom of the page in registration explaining the situation
> Changed register to join waitlist

- js/dashboard.js
I was a terrible person. Last name, First name is correct.
> Swapped first and last name

- _scss/pages/_about.scss
- about.html
- faq.html
- hack-ideas.html
- index.html
- prizing.html
- schedule.html
- sponsors.html
Change images to use CDN sources
> Deploy image source changes

- _config.yml
- _data/config.yml
- _includes/footer.html
- _includes/header.html
- _layouts/homepage.html
- about.html
- faq.html
- js/verify.js
- register.html
- schedule.html
- sponsors.html
This doesn't include the live-site.  Updates for the live site will be coming in a later change.
> Update date references in template

- _data/hack-ideas.yml
- hack-ideas.html
Update the hack ideas page to a new layout with modal popups.
> Revuc 2020 development update hack ideas

- _layouts/homepage.html
- _scss/components/_hero.scss
- _scss/components/_registration.scss
- js/subscribe.js
- register.html
> homepage renovation

- _data/schedule.yml
- _data/sponsors.yml
- about.html
- faq.html
- schedule.html
FAQs and About pages need copies from Director/Logistics!
> Cleaned up Schedule, Sponsors

- _scss/components/_call-to-action.scss
Center aligned body of the text
> aligned text on schedule page

- _data/schedule.yml
Updated schedule webpage by using info from https://docs.google.com/spreadsheets/d/18uDSxHTYpkf2s9EuHX0e9WedI4OjNCaFSI47VtpeNIs/edit#gid=0
> Updated schedule webpage

- _data/config.yml
> Remove MLH banner ,updating to bw 2023 banner

- _layouts/homepage.html
Removed the recapcha div to experiment with the bug
> remove recapcha div

- _layouts/homepage.html
- _scss/components/_header.scss
- _scss/components/_hero.scss
- interestform.html
- js/app.js
- js/header.js
- js/preRegistration.js
- Fix mobile navbar: Now should only show nav item when click on hamburger menu
- Fix hero layout: Now particles should be full 100 view height and content will be center (thanks to Flexbox) and no more overflow
> Fix hero and navbar on mobile and desktop

- _data/config.yml
- _includes/header.html
- _layouts/homepage.html
- _scss/components/_header.scss
- _scss/components/_hero.scss
- _scss/components/_registration.scss
- _scss/type/_base.scss
- Fixed hero logo overlapping bug
- Moved the date text to a new line for better visual hierarchy
- Fixed hover state of register button
> Small hero fixes

- _includes/header.html
- _scss/_intl-tel-input.scss
- _scss/_reset.scss
- _scss/components/_header.scss
- js/intl-tel-input.js
- js/register.js
- register.html
Make an international phone input that have a selection for countries and automatically add its corresponding country code, so that the UX is better for users who forget, or don't know, or just not used to typing country code. The library used, `intl-tel-input` also has number validation, so that is nice.
The PR also slightly improves the UX by scrolling-into-view fields that have validation errors, and use native `required` html validation
Changes have been manually tested.
> Make international phone input for register page

- _data/sponsors.yml
- _scss/_variables.scss
- _scss/components/_section.scss
- _scss/pages/_sponsors.scss
- index.html
- sponsors.html
- Added 2023 sponsors
- Changed to use `<img>` elements solely instead of `<picture>` element because that seems to never got used
- Updated styling and yml config files so now each row is a sponsor tier, and lower tier logos are a bit smaller than higher tiers.
- Increased the max-width of the sponsor section to 1300px
> Update sponsors for 2023 and use new styling

- _data/schedule.yml
- _data/sponsors.yml
- _scss/_variables.scss
- _scss/pages/_sponsors.scss
- schedule.html
- sponsors.html
- Added tentative schedule, and a disclaimer.
- New sponsor page design where we group sponsors by tiers: high (Diamon and Plat), medium (Gold and Silver), and others
> Update schedule and new sponsor page design
